"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { temples } from "../data/temples"
import TempleMap from "../components/TempleMap"

const provinces = ["All Provinces", "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan"]
const firstTempleId = "sri-lankan-buddhist-society-calgary"

export default function Home() {
  const [query, setQuery] = useState("")
  const [province, setProvince] = useState("All Provinces")
  const filtered = useMemo(() => {
    const matches = temples.filter((t) => { const text = `${t.name} ${t.city} ${t.province} ${t.address}`.toLowerCase(); return (province === "All Provinces" || t.province === province) && text.includes(query.toLowerCase()) })
    return matches.sort((a,b) => a.id === firstTempleId ? -1 : b.id === firstTempleId ? 1 : 0)
  }, [query, province])
  return <main style={{ minHeight:"100vh", backgroundImage:"linear-gradient(rgba(250,248,244,.88),rgba(244,240,233,.94)),url('/IMG_0323.JPG')", backgroundSize:"cover", backgroundPosition:"center top", backgroundAttachment:"fixed", color:"#2b241e" }}>
    <header style={{ backgroundImage:"linear-gradient(90deg,rgba(63,34,17,.92),rgba(111,61,29,.74)),url('/IMG_0323.JPG')", backgroundSize:"cover", backgroundPosition:"center", color:"white", padding:"18px 20px 52px", boxShadow:"0 8px 30px rgba(70,40,15,.14)" }}><div style={{maxWidth:1180,margin:"0 auto"}}><nav style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,marginBottom:40}}><Link href="/" style={{color:'#fff',textDecoration:'none',fontWeight:850,fontSize:16}}>☸️ Sri Lankan Buddhist Temples in Canada</Link><div style={{display:'flex',gap:20,fontSize:14,fontWeight:750,flexWrap:'wrap'}}><Link href="/" style={{color:'#fff',textDecoration:'none'}}>Home</Link><Link href="/about" style={{color:'#fff',textDecoration:'none'}}>About</Link><Link href="/contact" style={{color:'#fff',textDecoration:'none'}}>Contact Us</Link></div></nav><div style={{maxWidth:820}}><div style={{fontSize:13,letterSpacing:1.5,textTransform:"uppercase",opacity:.8,marginBottom:10}}>Canada Buddhist Temple Directory</div><h1 style={{margin:0,fontSize:"clamp(32px,6vw,54px)",lineHeight:1.06,letterSpacing:-1.5}}>Find Sri Lankan Buddhist temples across Canada</h1><p style={{margin:"16px 0 0",maxWidth:720,fontSize:"clamp(16px,2.2vw,19px)",lineHeight:1.6,color:"rgba(255,255,255,.9)"}}>A simple public directory designed to help people discover temples, monasteries, meditation centres and Buddhist communities in Canada.</p></div></div></header>
    <section style={{maxWidth:1180,margin:"-28px auto 0",padding:"0 20px 60px",position:"relative"}}><div style={{background:"rgba(255,255,255,.94)",backdropFilter:"blur(8px)",border:"1px solid rgba(232,224,214,.9)",borderRadius:20,padding:18,boxShadow:"0 16px 38px rgba(62,43,25,.11)"}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 250px",gap:12}}><input aria-label="Search temples" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by temple, city or province..." style={{width:"100%",padding:"15px 16px",border:"1px solid #d8d0c6",borderRadius:12,fontSize:16,background:"rgba(255,255,255,.96)",outline:"none"}}/><select aria-label="Filter by province" value={province} onChange={e=>setProvince(e.target.value)} style={{width:"100%",padding:"15px 16px",border:"1px solid #d8d0c6",borderRadius:12,fontSize:16,background:"rgba(255,255,255,.96)",color:"#33291f"}}>{provinces.map(p=><option key={p}>{p}</option>)}</select></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:14}}><span style={{color:"#65584d",fontSize:14,fontWeight:650}}>{filtered.length} {filtered.length===1?"temple":"temples"} found</span>{(query||province!=="All Provinces")&&<button onClick={()=>{setQuery("");setProvince("All Provinces")}} style={{border:0,background:"transparent",color:"#7a451f",fontWeight:750,cursor:"pointer"}}>Clear filters</button>}</div></div>
      <section style={{marginTop:34}}><div style={{marginBottom:13}}><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#8a6c50'}}>EXPLORE BY MAP</div><h2 style={{margin:'5px 0 0',fontSize:"clamp(24px,3vw,32px)",color:'#35271c'}}>Temple locations</h2><p style={{margin:"6px 0 0",color:'#75685d',fontSize:14}}>Touch a ☸️ marker for temple details and a direct Google Maps link.</p></div><div style={{background:"rgba(255,255,255,.72)",backdropFilter:"blur(5px)",borderRadius:20,padding:10,border:"1px solid rgba(229,221,211,.85)",boxShadow:"0 10px 28px rgba(62,43,25,.07)"}}><TempleMap temples={filtered}/></div></section>
      <section style={{marginTop:38}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:14,gap:15}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#8a6c50'}}>DIRECTORY</div><h2 style={{margin:'5px 0 0',fontSize:"clamp(24px,3vw,32px)",color:'#35271c'}}>Temples & Buddhist centres</h2><p style={{margin:"6px 0 0",color:'#75685d',fontSize:14}}>Open a listing for address, contact and map information.</p></div><span style={{background:'#eee5d9',color:'#63401f',padding:'7px 11px',borderRadius:999,fontSize:13,fontWeight:750,whiteSpace:'nowrap'}}>{filtered.length} found</span></div>{filtered.length===0?<div style={{padding:32,background:"rgba(255,255,255,.94)",borderRadius:16,textAlign:"center",border:'1px solid #e5ddd3'}}>No temples match your search or province filter.</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(270px,1fr))',gap:14}}>{filtered.map((t,index)=><Link key={t.id} href={`/temples/${t.id}`} style={{textDecoration:'none',color:'inherit'}}><article style={{height:'100%',padding:21,background:index===0?'linear-gradient(145deg,rgba(255,250,239,.98),rgba(255,255,255,.94))':'rgba(255,255,255,.92)',backdropFilter:'blur(5px)',borderRadius:17,border:index===0?'1px solid #d6b987':'1px solid rgba(229,221,211,.9)',boxShadow:index===0?'0 8px 24px rgba(117,75,31,.12)':'none'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:10}}><div style={{fontSize:24}}>☸️</div>{index===0?<span style={{fontSize:11,fontWeight:800,color:'#7a541f',background:'#f0e0bd',padding:'5px 8px',borderRadius:999}}>Featured</span>:<span style={{fontSize:12,fontWeight:750,color:'#86694f'}}>{t.province}</span>}</div><h3 style={{margin:'12px 0 9px',fontSize:18,lineHeight:1.3,color:'#392a1d'}}>{t.name}</h3><p style={{margin:'0 0 15px',color:'#6b625b',lineHeight:1.5,fontSize:14}}>{t.address}, {t.city}{t.postalCode?` ${t.postalCode}`:""}</p><span style={{color:'#7a451f',fontWeight:750,fontSize:14}}>View temple details →</span></article></Link>)}</div>}</section>
      <footer style={{marginTop:52,padding:'24px 0 8px',borderTop:'1px solid #ded5ca',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap',color:'#776c62',fontSize:12,lineHeight:1.6}}><span>© {new Date().getFullYear()} Sri Lankan Buddhist Temples in Canada</span><span><Link href='/about'>About</Link> · <Link href='/contact'>Contact Us</Link> · Public-source directory · Map data © OpenStreetMap</span></footer>
    </section>
  </main>
}
